version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: framer-motion
    versions:
    - 3.6.7
    - 4.0.0
    - 4.0.2
    - 4.0.3
    - 4.1.10
    - 4.1.2
    - 4.1.3
    - 4.1.5
    - 4.1.6
    - 4.1.8
    - 4.1.9
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.7.2
    - 13.0.0
    - 13.0.10
    - 13.0.13
    - 13.0.16
    - 13.0.2
    - 13.1.2
    - 13.1.3
    - 13.1.5
  - dependency-name: twin.macro
    versions:
    - 2.2.0
    - 2.3.1
    - 2.3.2
